/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as InvitationsIdRouteImport } from './routes/invitations/$id'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as WebTosRouteImport } from './routes/_web/tos'
import { Route as WebSupportRouteImport } from './routes/_web/support'
import { Route as WebPrivacyPolicyRouteImport } from './routes/_web/privacy-policy'
import { Route as WebContactRouteImport } from './routes/_web/contact'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as WebPosterRouteRouteImport } from './routes/_web/poster/route'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as WebPosterIndexRouteImport } from './routes/_web/poster/index'
import { Route as WebNewsroomIndexRouteImport } from './routes/_web/newsroom/index'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminObservabilityRouteImport } from './routes/app/admin/observability'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WebNewsroomArticleIdRouteImport } from './routes/_web/newsroom/$articleId'
import { Route as AppProjectIdIndexRouteImport } from './routes/app/project/$id/index'
import { Route as AppOrganizationIdIndexRouteImport } from './routes/app/organization/$id/index'
import { Route as AppProjectIdSettingsRouteImport } from './routes/app/project/$id/settings'
import { Route as AppOrganizationIdSettingsRouteImport } from './routes/app/organization/$id/settings'
import { Route as AppOrganizationIdMembersRouteImport } from './routes/app/organization/$id/members'
import { Route as ApiOgPageSlugRouteImport } from './routes/api/og/page/$slug'
import { Route as ApiOgNewsroomArticleIdRouteImport } from './routes/api/og/newsroom/$articleId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const InvitationsIdRoute = InvitationsIdRouteImport.update({
  id: '/invitations/$id',
  path: '/invitations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WebTosRoute = WebTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebSupportRoute = WebSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebPrivacyPolicyRoute = WebPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebContactRoute = WebContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const WebPosterRouteRoute = WebPosterRouteRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const WebPosterIndexRoute = WebPosterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebPosterRouteRoute,
} as any)
const WebNewsroomIndexRoute = WebNewsroomIndexRouteImport.update({
  id: '/newsroom/',
  path: '/newsroom/',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminObservabilityRoute = AppAdminObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WebNewsroomArticleIdRoute = WebNewsroomArticleIdRouteImport.update({
  id: '/newsroom/$articleId',
  path: '/newsroom/$articleId',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppProjectIdIndexRoute = AppProjectIdIndexRouteImport.update({
  id: '/project/$id/',
  path: '/project/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationIdIndexRoute = AppOrganizationIdIndexRouteImport.update({
  id: '/organization/$id/',
  path: '/organization/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectIdSettingsRoute = AppProjectIdSettingsRouteImport.update({
  id: '/project/$id/settings',
  path: '/project/$id/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationIdSettingsRoute =
  AppOrganizationIdSettingsRouteImport.update({
    id: '/organization/$id/settings',
    path: '/organization/$id/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationIdMembersRoute =
  AppOrganizationIdMembersRouteImport.update({
    id: '/organization/$id/members',
    path: '/organization/$id/members',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiOgPageSlugRoute = ApiOgPageSlugRouteImport.update({
  id: '/api/og/page/$slug',
  path: '/api/og/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgNewsroomArticleIdRoute = ApiOgNewsroomArticleIdRouteImport.update({
  id: '/api/og/newsroom/$articleId',
  path: '/api/og/newsroom/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/poster': typeof WebPosterRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/contact': typeof WebContactRoute
  '/privacy-policy': typeof WebPrivacyPolicyRoute
  '/support': typeof WebSupportRoute
  '/tos': typeof WebTosRoute
  '/api/health': typeof ApiHealthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/app/': typeof AppIndexRoute
  '/newsroom/$articleId': typeof WebNewsroomArticleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/admin/observability': typeof AppAdminObservabilityRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/newsroom/': typeof WebNewsroomIndexRoute
  '/poster/': typeof WebPosterIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/api/og/newsroom/$articleId': typeof ApiOgNewsroomArticleIdRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
  '/app/organization/$id/members': typeof AppOrganizationIdMembersRoute
  '/app/organization/$id/settings': typeof AppOrganizationIdSettingsRoute
  '/app/project/$id/settings': typeof AppProjectIdSettingsRoute
  '/app/organization/$id/': typeof AppOrganizationIdIndexRoute
  '/app/project/$id/': typeof AppProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof WebContactRoute
  '/privacy-policy': typeof WebPrivacyPolicyRoute
  '/support': typeof WebSupportRoute
  '/tos': typeof WebTosRoute
  '/api/health': typeof ApiHealthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/': typeof WebIndexRoute
  '/app': typeof AppIndexRoute
  '/newsroom/$articleId': typeof WebNewsroomArticleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/admin/observability': typeof AppAdminObservabilityRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/newsroom': typeof WebNewsroomIndexRoute
  '/poster': typeof WebPosterIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/api/og/newsroom/$articleId': typeof ApiOgNewsroomArticleIdRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
  '/app/organization/$id/members': typeof AppOrganizationIdMembersRoute
  '/app/organization/$id/settings': typeof AppOrganizationIdSettingsRoute
  '/app/project/$id/settings': typeof AppProjectIdSettingsRoute
  '/app/organization/$id': typeof AppOrganizationIdIndexRoute
  '/app/project/$id': typeof AppProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_web': typeof WebRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_web/poster': typeof WebPosterRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/_web/contact': typeof WebContactRoute
  '/_web/privacy-policy': typeof WebPrivacyPolicyRoute
  '/_web/support': typeof WebSupportRoute
  '/_web/tos': typeof WebTosRoute
  '/api/health': typeof ApiHealthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/invitations/$id': typeof InvitationsIdRoute
  '/_web/': typeof WebIndexRoute
  '/app/': typeof AppIndexRoute
  '/_web/newsroom/$articleId': typeof WebNewsroomArticleIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/admin/observability': typeof AppAdminObservabilityRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/_web/newsroom/': typeof WebNewsroomIndexRoute
  '/_web/poster/': typeof WebPosterIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/api/og/newsroom/$articleId': typeof ApiOgNewsroomArticleIdRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
  '/app/organization/$id/members': typeof AppOrganizationIdMembersRoute
  '/app/organization/$id/settings': typeof AppOrganizationIdSettingsRoute
  '/app/project/$id/settings': typeof AppProjectIdSettingsRoute
  '/app/organization/$id/': typeof AppOrganizationIdIndexRoute
  '/app/project/$id/': typeof AppProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/poster'
    | '/app/admin'
    | '/contact'
    | '/privacy-policy'
    | '/support'
    | '/tos'
    | '/api/health'
    | '/app/dashboard'
    | '/invitations/$id'
    | '/app/'
    | '/newsroom/$articleId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/admin/observability'
    | '/app/admin/users'
    | '/newsroom/'
    | '/poster/'
    | '/app/admin/'
    | '/api/og/newsroom/$articleId'
    | '/api/og/page/$slug'
    | '/app/organization/$id/members'
    | '/app/organization/$id/settings'
    | '/app/project/$id/settings'
    | '/app/organization/$id/'
    | '/app/project/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/contact'
    | '/privacy-policy'
    | '/support'
    | '/tos'
    | '/api/health'
    | '/app/dashboard'
    | '/invitations/$id'
    | '/'
    | '/app'
    | '/newsroom/$articleId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/admin/observability'
    | '/app/admin/users'
    | '/newsroom'
    | '/poster'
    | '/app/admin'
    | '/api/og/newsroom/$articleId'
    | '/api/og/page/$slug'
    | '/app/organization/$id/members'
    | '/app/organization/$id/settings'
    | '/app/project/$id/settings'
    | '/app/organization/$id'
    | '/app/project/$id'
  id:
    | '__root__'
    | '/_web'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/_web/poster'
    | '/app/admin'
    | '/_web/contact'
    | '/_web/privacy-policy'
    | '/_web/support'
    | '/_web/tos'
    | '/api/health'
    | '/app/dashboard'
    | '/invitations/$id'
    | '/_web/'
    | '/app/'
    | '/_web/newsroom/$articleId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/admin/observability'
    | '/app/admin/users'
    | '/_web/newsroom/'
    | '/_web/poster/'
    | '/app/admin/'
    | '/api/og/newsroom/$articleId'
    | '/api/og/page/$slug'
    | '/app/organization/$id/members'
    | '/app/organization/$id/settings'
    | '/app/project/$id/settings'
    | '/app/organization/$id/'
    | '/app/project/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebRouteRoute: typeof WebRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  InvitationsIdRoute: typeof InvitationsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiOgNewsroomArticleIdRoute: typeof ApiOgNewsroomArticleIdRoute
  ApiOgPageSlugRoute: typeof ApiOgPageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/invitations/$id': {
      id: '/invitations/$id'
      path: '/invitations/$id'
      fullPath: '/invitations/$id'
      preLoaderRoute: typeof InvitationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/tos': {
      id: '/_web/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof WebTosRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/support': {
      id: '/_web/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof WebSupportRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/privacy-policy': {
      id: '/_web/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof WebPrivacyPolicyRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/contact': {
      id: '/_web/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof WebContactRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_web/poster': {
      id: '/_web/poster'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof WebPosterRouteRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_web/poster/': {
      id: '/_web/poster/'
      path: '/'
      fullPath: '/poster/'
      preLoaderRoute: typeof WebPosterIndexRouteImport
      parentRoute: typeof WebPosterRouteRoute
    }
    '/_web/newsroom/': {
      id: '/_web/newsroom/'
      path: '/newsroom'
      fullPath: '/newsroom/'
      preLoaderRoute: typeof WebNewsroomIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/observability': {
      id: '/app/admin/observability'
      path: '/observability'
      fullPath: '/app/admin/observability'
      preLoaderRoute: typeof AppAdminObservabilityRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/newsroom/$articleId': {
      id: '/_web/newsroom/$articleId'
      path: '/newsroom/$articleId'
      fullPath: '/newsroom/$articleId'
      preLoaderRoute: typeof WebNewsroomArticleIdRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/app/project/$id/': {
      id: '/app/project/$id/'
      path: '/project/$id'
      fullPath: '/app/project/$id/'
      preLoaderRoute: typeof AppProjectIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organization/$id/': {
      id: '/app/organization/$id/'
      path: '/organization/$id'
      fullPath: '/app/organization/$id/'
      preLoaderRoute: typeof AppOrganizationIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/project/$id/settings': {
      id: '/app/project/$id/settings'
      path: '/project/$id/settings'
      fullPath: '/app/project/$id/settings'
      preLoaderRoute: typeof AppProjectIdSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organization/$id/settings': {
      id: '/app/organization/$id/settings'
      path: '/organization/$id/settings'
      fullPath: '/app/organization/$id/settings'
      preLoaderRoute: typeof AppOrganizationIdSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organization/$id/members': {
      id: '/app/organization/$id/members'
      path: '/organization/$id/members'
      fullPath: '/app/organization/$id/members'
      preLoaderRoute: typeof AppOrganizationIdMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/og/page/$slug': {
      id: '/api/og/page/$slug'
      path: '/api/og/page/$slug'
      fullPath: '/api/og/page/$slug'
      preLoaderRoute: typeof ApiOgPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/newsroom/$articleId': {
      id: '/api/og/newsroom/$articleId'
      path: '/api/og/newsroom/$articleId'
      fullPath: '/api/og/newsroom/$articleId'
      preLoaderRoute: typeof ApiOgNewsroomArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WebPosterRouteRouteChildren {
  WebPosterIndexRoute: typeof WebPosterIndexRoute
}

const WebPosterRouteRouteChildren: WebPosterRouteRouteChildren = {
  WebPosterIndexRoute: WebPosterIndexRoute,
}

const WebPosterRouteRouteWithChildren = WebPosterRouteRoute._addFileChildren(
  WebPosterRouteRouteChildren,
)

interface WebRouteRouteChildren {
  WebPosterRouteRoute: typeof WebPosterRouteRouteWithChildren
  WebContactRoute: typeof WebContactRoute
  WebPrivacyPolicyRoute: typeof WebPrivacyPolicyRoute
  WebSupportRoute: typeof WebSupportRoute
  WebTosRoute: typeof WebTosRoute
  WebIndexRoute: typeof WebIndexRoute
  WebNewsroomArticleIdRoute: typeof WebNewsroomArticleIdRoute
  WebNewsroomIndexRoute: typeof WebNewsroomIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebPosterRouteRoute: WebPosterRouteRouteWithChildren,
  WebContactRoute: WebContactRoute,
  WebPrivacyPolicyRoute: WebPrivacyPolicyRoute,
  WebSupportRoute: WebSupportRoute,
  WebTosRoute: WebTosRoute,
  WebIndexRoute: WebIndexRoute,
  WebNewsroomArticleIdRoute: WebNewsroomArticleIdRoute,
  WebNewsroomIndexRoute: WebNewsroomIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

interface AppAdminRouteRouteChildren {
  AppAdminObservabilityRoute: typeof AppAdminObservabilityRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminObservabilityRoute: AppAdminObservabilityRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationIdMembersRoute: typeof AppOrganizationIdMembersRoute
  AppOrganizationIdSettingsRoute: typeof AppOrganizationIdSettingsRoute
  AppProjectIdSettingsRoute: typeof AppProjectIdSettingsRoute
  AppOrganizationIdIndexRoute: typeof AppOrganizationIdIndexRoute
  AppProjectIdIndexRoute: typeof AppProjectIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrganizationIdMembersRoute: AppOrganizationIdMembersRoute,
  AppOrganizationIdSettingsRoute: AppOrganizationIdSettingsRoute,
  AppProjectIdSettingsRoute: AppProjectIdSettingsRoute,
  AppOrganizationIdIndexRoute: AppOrganizationIdIndexRoute,
  AppProjectIdIndexRoute: AppProjectIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WebRouteRoute: WebRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  InvitationsIdRoute: InvitationsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiOgNewsroomArticleIdRoute: ApiOgNewsroomArticleIdRoute,
  ApiOgPageSlugRoute: ApiOgPageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
