/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as WebTosRouteImport } from './routes/_web/tos'
import { Route as WebSupportRouteImport } from './routes/_web/support'
import { Route as WebPrivacyPolicyRouteImport } from './routes/_web/privacy-policy'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminOsmDataRouteImport } from './routes/app/admin/osm-data'
import { Route as AppAdminObservabilityRouteImport } from './routes/app/admin/observability'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOgPageSlugRouteImport } from './routes/api/og/page/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WebTosRoute = WebTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebSupportRoute = WebSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebPrivacyPolicyRoute = WebPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => WebRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminOsmDataRoute = AppAdminOsmDataRouteImport.update({
  id: '/osm-data',
  path: '/osm-data',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminObservabilityRoute = AppAdminObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPageSlugRoute = ApiOgPageSlugRouteImport.update({
  id: '/api/og/page/$slug',
  path: '/api/og/page/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/privacy-policy': typeof WebPrivacyPolicyRoute
  '/support': typeof WebSupportRoute
  '/tos': typeof WebTosRoute
  '/api/health': typeof ApiHealthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/admin/observability': typeof AppAdminObservabilityRoute
  '/app/admin/osm-data': typeof AppAdminOsmDataRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/privacy-policy': typeof WebPrivacyPolicyRoute
  '/support': typeof WebSupportRoute
  '/tos': typeof WebTosRoute
  '/api/health': typeof ApiHealthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/': typeof WebIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/admin/observability': typeof AppAdminObservabilityRoute
  '/app/admin/osm-data': typeof AppAdminOsmDataRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_web': typeof WebRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/_web/privacy-policy': typeof WebPrivacyPolicyRoute
  '/_web/support': typeof WebSupportRoute
  '/_web/tos': typeof WebTosRoute
  '/api/health': typeof ApiHealthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/_web/': typeof WebIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/admin/observability': typeof AppAdminObservabilityRoute
  '/app/admin/osm-data': typeof AppAdminOsmDataRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/api/og/page/$slug': typeof ApiOgPageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/app/admin'
    | '/privacy-policy'
    | '/support'
    | '/tos'
    | '/api/health'
    | '/app/dashboard'
    | '/app/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/admin/observability'
    | '/app/admin/osm-data'
    | '/app/admin/users'
    | '/app/admin/'
    | '/api/og/page/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/privacy-policy'
    | '/support'
    | '/tos'
    | '/api/health'
    | '/app/dashboard'
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/admin/observability'
    | '/app/admin/osm-data'
    | '/app/admin/users'
    | '/app/admin'
    | '/api/og/page/$slug'
  id:
    | '__root__'
    | '/_web'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/app/admin'
    | '/_web/privacy-policy'
    | '/_web/support'
    | '/_web/tos'
    | '/api/health'
    | '/app/dashboard'
    | '/_web/'
    | '/app/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/app/admin/observability'
    | '/app/admin/osm-data'
    | '/app/admin/users'
    | '/app/admin/'
    | '/api/og/page/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebRouteRoute: typeof WebRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiOgPageSlugRoute: typeof ApiOgPageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/tos': {
      id: '/_web/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof WebTosRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/support': {
      id: '/_web/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof WebSupportRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/privacy-policy': {
      id: '/_web/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof WebPrivacyPolicyRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/osm-data': {
      id: '/app/admin/osm-data'
      path: '/osm-data'
      fullPath: '/app/admin/osm-data'
      preLoaderRoute: typeof AppAdminOsmDataRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/observability': {
      id: '/app/admin/observability'
      path: '/observability'
      fullPath: '/app/admin/observability'
      preLoaderRoute: typeof AppAdminObservabilityRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/page/$slug': {
      id: '/api/og/page/$slug'
      path: '/api/og/page/$slug'
      fullPath: '/api/og/page/$slug'
      preLoaderRoute: typeof ApiOgPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WebRouteRouteChildren {
  WebPrivacyPolicyRoute: typeof WebPrivacyPolicyRoute
  WebSupportRoute: typeof WebSupportRoute
  WebTosRoute: typeof WebTosRoute
  WebIndexRoute: typeof WebIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebPrivacyPolicyRoute: WebPrivacyPolicyRoute,
  WebSupportRoute: WebSupportRoute,
  WebTosRoute: WebTosRoute,
  WebIndexRoute: WebIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

interface AppAdminRouteRouteChildren {
  AppAdminObservabilityRoute: typeof AppAdminObservabilityRoute
  AppAdminOsmDataRoute: typeof AppAdminOsmDataRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminObservabilityRoute: AppAdminObservabilityRoute,
  AppAdminOsmDataRoute: AppAdminOsmDataRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WebRouteRoute: WebRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiOgPageSlugRoute: ApiOgPageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
