import { dirname } from "node:path";

const LOGO_PATH = `${process.cwd()}/src/assets/logo.png`;
const OUTPUT_PATH = `${process.cwd()}/src/generated/logo-base64.ts`;

try {
  // Read logo file
  const logoFile = Bun.file(LOGO_PATH);
  const logoBuffer = await logoFile.arrayBuffer();
  const base64 = Buffer.from(logoBuffer).toString("base64");
  const dataUrl = `data:image/png;base64,${base64}`;

  // Create output directory if it doesn't exist
  const outputDir = dirname(OUTPUT_PATH);
  const mkdirProc = Bun.spawn(["mkdir", "-p", outputDir]);
  const mkdirExit = await mkdirProc.exited;

  if (mkdirExit !== 0) {
    const stderr = await new Response(
      mkdirProc.stderr
    ).text();
    throw new Error(`mkdir failed: ${stderr}`);
  }

  // Generate TypeScript file
  const content = `// This file is auto-generated by scripts/generate-logo-constant.ts
// Do not edit manually

export const LOGO_BASE64 = "${dataUrl}";
`;

  await Bun.write(OUTPUT_PATH, content);

  console.log(
    `✓ Logo base64 constant generated: ${OUTPUT_PATH}`
  );
  console.log(
    `  Logo size: ${(logoBuffer.byteLength / 1024).toFixed(2)} KB`
  );
  console.log(
    `  Base64 size: ${(base64.length / 1024).toFixed(2)} KB`
  );
} catch (error) {
  console.error("Failed to generate logo constant:", error);
  process.exit(1);
}
